[package]
name = "rkstreams"
version = "0.1.0"
authors = ["matthias-margush <matthias.margush@fundingcircle.com>"]
edition = "2018"

[dependencies]
env_logger = "0.6.1"
futures = "0.1.27"
log = "0.4"
rdkafka = "~0.21"
serde = "1.0.92"
serde_bytes = "0.11"
serde_json = "1.0"
